### ISSUE TITLE
bdb.BdbQuit error while training conll 2003

### ISSUE THREAD

**Issue by Sreyan88** [Alibaba-NLP/ACE#53]
Hi there! Great repo. I was trying to train the conll 2003 on the default conll_03_english.yaml and got this error.

```
Traceback (most recent call last):
  File "train.py", line 397, in <module>
    getattr(trainer,'train')(**train_config)
  File "/scratch/zt1/project/dmanocha-prj/user/sreyang/acl_baseline/ACE/flair/trainers/reinforcement_trainer.py", line 827, in train
    if macro_avg:
  File "/scratch/zt1/project/dmanocha-prj/user/sreyang/acl_baseline/ACE/flair/trainers/reinforcement_trainer.py", line 827, in train
    if macro_avg:
  File "/home/sreyang/scratch/anaconda3/envs/ace/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/sreyang/scratch/anaconda3/envs/ace/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

**Comment by wangxinyu0922** [comment]
Please remove line 826
